openai_api_key:  "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"
openai_organization: "org-qP0PlNB08VYCRGGgSgX23i9p"

stablediffusion_key: "kEX4l7XmW0EtQy0ATrPZlsUTLlhBBarONs5dSAmn9tUnGPpwiPL07nDLjMeQ"
model: "gpt-3.5-turbo"